version: '2.3'

services: 
  web:
    container_name: youtube-meta
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    stdin_open: true
    ports: 
      - "8000:8000"
      - "8022:22"
    expose:
      - "8080"
    volumes:
      - .:/workspace
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
